# Form implementation generated from reading ui file 'qt_game.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameForm(object):
    def setupUi(self, GameForm):
        GameForm.setObjectName("GameForm")
        GameForm.resize(600, 800)
        self.verticalLayoutWidget = QtWidgets.QWidget(GameForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 601, 801))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.game_id_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.game_id_label.setObjectName("game_id_label")
        self.verticalLayout.addWidget(self.game_id_label)
        self.status_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.opponent_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.opponent_label.setObjectName("opponent_label")
        self.verticalLayout.addWidget(self.opponent_label)
        self.color_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label.setObjectName("color_label")
        self.verticalLayout.addWidget(self.color_label)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.retranslateUi(GameForm)
        QtCore.QMetaObject.connectSlotsByName(GameForm)

    def retranslateUi(self, GameForm):
        _translate = QtCore.QCoreApplication.translate
        GameForm.setWindowTitle(_translate("GameForm", "Form"))
        self.game_id_label.setText(_translate("GameForm", "GameID:"))
        self.status_label.setText(_translate("GameForm", "Статус игры: "))
        self.opponent_label.setText(_translate("GameForm", "Ваш противник:"))
        self.color_label.setText(_translate("GameForm", "Ваш противник:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameForm = QtWidgets.QWidget()
    ui = Ui_GameForm()
    ui.setupUi(GameForm)
    GameForm.show()
    sys.exit(app.exec())
