# Form implementation generated from reading ui file 'qt_lobby.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LobbyForm(object):
    def setupUi(self, LobbyForm):
        LobbyForm.setObjectName("LobbyForm")
        LobbyForm.resize(600, 800)
        self.verticalLayoutWidget = QtWidgets.QWidget(LobbyForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 601, 801))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_layout = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.login_layout.setMaximumSize(QtCore.QSize(16777215, 20))
        self.login_layout.setObjectName("login_layout")
        self.verticalLayout.addWidget(self.login_layout)
        self.wins_layout = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wins_layout.setMaximumSize(QtCore.QSize(16777215, 20))
        self.wins_layout.setObjectName("wins_layout")
        self.verticalLayout.addWidget(self.wins_layout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pole_size_layout = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pole_size_layout.setObjectName("pole_size_layout")
        self.verticalLayout_2.addWidget(self.pole_size_layout)
        self.pole_size_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.pole_size_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pole_size_slider.setObjectName("pole_size_slider")
        self.verticalLayout_2.addWidget(self.pole_size_slider)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.create_game_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.create_game_button.setObjectName("create_game_button")
        self.horizontalLayout_2.addWidget(self.create_game_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(LobbyForm)
        QtCore.QMetaObject.connectSlotsByName(LobbyForm)

    def retranslateUi(self, LobbyForm):
        _translate = QtCore.QCoreApplication.translate
        LobbyForm.setWindowTitle(_translate("LobbyForm", "Form"))
        self.login_layout.setText(_translate("LobbyForm", "Ваш логин: "))
        self.wins_layout.setText(_translate("LobbyForm", "Количество побед: "))
        self.label.setText(_translate("LobbyForm", "Создать игру"))
        self.pole_size_layout.setText(_translate("LobbyForm", "Размер поля:"))
        self.create_game_button.setText(_translate("LobbyForm", "Создать"))
        self.label_2.setText(_translate("LobbyForm", "Создать игру"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LobbyForm = QtWidgets.QWidget()
    ui = Ui_LobbyForm()
    ui.setupUi(LobbyForm)
    LobbyForm.show()
    sys.exit(app.exec())
